#!/usr/bin/env python3
"""Emit the generated dictionary Swift files from committed TSV data.

Inputs (committed in this directory):
  dict_table.tsv    term<TAB>replacement -- IBM TTS dictionary respellings
                    (eigencrow/IBMTTSDictionaries, community) the engine
                    speaks verbatim. Whole-word, case-sensitive, longest
                    first.
  stress_kept.tsv   word<TAB>phonemes<TAB>profile -- stress fixes: TruVoice's
                    own phones with `1` moved to the IBM primary. Every row
                    verified (lexicon-installed trace shows `1` at IBM's
                    primary, audio speaks). 2-syllable words first, then
                    3-syllable, to the engine's 5,000-entry user-lexicon cap.

Outputs:
  ../Sources/TruVoiceCore/Dictionary.generated.swift
  ../Sources/TruVoiceKit/StressLexicon.generated.swift

Method and skipped cases: see README.md in this directory.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(os.path.dirname(os.path.dirname(HERE)), "Sources")


def read_tsv(name):
    rows = []
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line:
                rows.append(line.split("\t"))
    return rows


def swift_escape(s):
    assert '"' not in s and "\\" not in s and "\n" not in s, repr(s)
    return s


def emit_dictionary(pairs):
    head = [
        "// Dictionary.generated.swift -- DO NOT EDIT.",
        "// Generated by tools/dict_audit/gen_tables.py from dict_table.tsv",
        "// (IBM TTS dictionary respellings, community profile).",
        "// %d whole-word, case-sensitive (term, replacement) pairs. The engine" % len(pairs),
        "// speaks every replacement verbatim; each was verified to synthesise",
        "// nonzero audio on the vendored engine before being listed here.",
        "// Method and skipped cases: see tools/dict_audit/README.md.",
        "import Foundation",
        "",
        "extension SSMLText {",
        "    /// Dictionary respellings, longest term first so a longer key",
        "    /// settles before any of its prefixes.",
        "    static let dictionaryTable: [(term: String, replacement: String)] = [",
    ]
    body = ['        ("%s", "%s"),' % (swift_escape(t), swift_escape(r)) for t, r in pairs]
    tail = ["    ]", "}", ""]
    with open(os.path.join(SRC, "TruVoiceCore", "Dictionary.generated.swift"),
              "w", encoding="utf-8") as f:
        f.write("\n".join(head + body + tail))


def emit_stress(rows):
    head = [
        "// StressLexicon.generated.swift -- DO NOT EDIT.",
        "// Generated by tools/dict_audit/gen_tables.py from stress_kept.tsv",
        "// (IBM TTS dictionary stress triage, community profile).",
        "// %d (word, phonemes) entries: TruVoice's own phones with `1` moved" % len(rows),
        "// to the IBM primary. Each verified: with the entry installed the",
        "// trace shows `1` at IBM's primary and the audio speaks. 2-syllable",
        "// words first, then 3-syllable, to the engine's 5,000-entry",
        "// user-lexicon cap (hand entries in TruVoice.lexiconEntries plus",
        "// these stay under it).",
        "// Method and skipped cases: see tools/dict_audit/README.md.",
        "import Foundation",
        "",
        "extension TruVoice {",
        "    /// Machine-verified stress fixes. Installed after `lexiconEntries`;",
        "    /// keys never collide with the hand list (checked at generation).",
        "    static let generatedLexiconEntries: [(word: String, phonemes: String)] = [",
    ]
    body = ['        ("%s", "%s"),' % (swift_escape(w), swift_escape(v)) for w, v, _ in rows]
    tail = ["    ]", "}", ""]
    with open(os.path.join(SRC, "TruVoiceKit", "StressLexicon.generated.swift"),
              "w", encoding="utf-8") as f:
        f.write("\n".join(head + body + tail))


def main():
    pairs = read_tsv("dict_table.tsv")
    emit_dictionary(pairs)
    print("dictionary:", len(pairs))
    rows = read_tsv("stress_kept.tsv")
    assert all(len(r) == 3 for r in rows)
    emit_stress(rows)
    print("stress:", len(rows))


main()
